name: CI

on:
  push:
    branches:
      - '!master'
  pull_request:
  workflow_dispatch:

jobs:
  test-dotnet:
    name: .NET Tests
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Install dependencies
        run: dotnet tool install --global dotnet-reportgenerator-globaltool

      - name: Restore dependencies 
        run: dotnet restore src/WeatherReport.sln

      - name: Build
        run: dotnet build src/WeatherReport.sln --no-restore

      - name: Test
        run: dotnet test src/WeatherReport.sln --no-build --verbosity normal --collect:"XPlat Code Coverage" --logger trx --results-directory coverage

      - name: Merge reports
        run: reportgenerator "-reports:coverage/**/coverage.cobertura.xml" "-targetdir:coverage" "-reporttypes:Cobertura"

      - name: Code coverage report
        uses: insightsengineering/coverage-action@v2
        with:
          path: coverage/Cobertura.xml
          fail: false
          diff: false